AllSuiteA.bin: AllSuiteA.asm
	acme -o AllSuiteA.bin AllSuiteA.asm

test1.bin: test1.asm
	acme -o test1.bin test1.asm

test2.bin: test2.asm
	acme -o test2.bin test2.asm

test3.bin: test3.asm
	acme -o test3.bin test3.asm

test-illegal-opcode-xaa-michael-steil.bin: test-illegal-opcode-xaa-michael-steil.asm
	acme -o test-illegal-opcode-xaa-michael-steil.bin test-illegal-opcode-xaa-michael-steil.asm

clean:
	rm -f AllSuiteA.bin test1.bin
