AllSuiteA.bin: AllSuiteA.asm
	acme -o AllSuiteA.bin AllSuiteA.asm

test1.bin: test1.asm
	acme -o test1.bin test1.asm

test2.bin: test2.asm
	acme -o test2.bin test2.asm

clean:
	rm -f AllSuiteA.bin test1.bin
