all:
	( cd 4001 ; make )
	( cd 4002 ; make )
	( cd 4003 ; make )
	( cd 4004 ; make )
	( cd 6502 ; make )

clean:
	( cd 4001 ; make clean )
	( cd 4002 ; make clean )
	( cd 4003 ; make clean )
	( cd 4004 ; make clean )
	( cd 6502 ; make clean )
